const mongoose = require('mongoose');
const Quiz = require('./models/Quiz');
const Question = require('./models/Question');
const User = require('./models/User');
const bcrypt = require('bcryptjs');
require('dotenv').config();

async function seedTrendingApp() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');

    // Clear existing data
    // await Quiz.deleteMany({});
    // await Question.deleteMany({});
    // await User.deleteMany({});
    // console.log('Cleared existing data');

    // Create admin user
    let adminUser = await User.findOne({ email: 'admin@quiz.com' });
    if (!adminUser) {
      const hashedPassword = await bcrypt.hash('admin@quiz.com', 12);
      adminUser = await User.create({
        name: 'Admin',
        email: 'admin@quiz.com',
        password: hashedPassword,
        role: 'admin'
      });
    }

    // Create 20 questions per language - 140 total questions
    const questions = [
      
      // HTML Questions (20) - Modern Web Development
      {
        questionTitle: 'What does HTML5 stand for?',
        problemStatement: 'HTML5 is the latest version of the HTML standard.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'HTML',
        options: [
          'Hyper Text Markup Language 5',
          'High Tech Modern Language 5',
          'Home Tool Markup Language 5',
          'Hyperlinks and Text Markup Language 5'
        ],
        correctAnswer: 'Hyper Text Markup Language 5',
        explanation: 'HTML5 stands for Hyper Text Markup Language 5, the latest HTML standard.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Web Development'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 element is used for drawing graphics?',
        problemStatement: 'HTML5 introduced new elements for graphics and multimedia.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'HTML',
        options: ['<graphics>', '<draw>', '<canvas>', '<svg>'],
        correctAnswer: '<canvas>',
        explanation: 'The <canvas> element is used for drawing graphics via JavaScript.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Canvas', 'Graphics'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 attribute is used for client-side form validation?',
        problemStatement: 'HTML5 provides built-in form validation attributes.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'HTML',
        options: ['validate', 'required', 'check', 'must'],
        correctAnswer: 'required',
        explanation: 'The required attribute specifies that an input field must be filled out.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Forms', 'Validation'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 element is used for playing video content?',
        problemStatement: 'HTML5 introduced native multimedia support.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'HTML',
        options: ['<video>', '<media>', '<movie>', '<play>'],
        correctAnswer: '<video>',
        explanation: 'The <video> element is used to embed video content in HTML5.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Video', 'Multimedia'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 semantic element represents navigation links?',
        problemStatement: 'HTML5 introduced semantic elements for better document structure.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'HTML',
        options: ['<navigation>', '<nav>', '<navbar>', '<menu>'],
        correctAnswer: '<nav>',
        explanation: 'The <nav> element represents a section of navigation links.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Semantic', 'Navigation'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 input type is used for email addresses?',
        problemStatement: 'HTML5 introduced specialized input types for better user experience.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'HTML',
        options: ['<input type="mail">', '<input type="email">', '<input type="address">', '<input type="e-mail">'],
        correctAnswer: '<input type="email">',
        explanation: 'The email input type provides built-in email validation.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Forms', 'Input Types'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 element is used for self-contained content?',
        problemStatement: 'HTML5 semantic elements help define content structure.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'HTML',
        options: ['<content>', '<section>', '<article>', '<div>'],
        correctAnswer: '<article>',
        explanation: 'The <article> element represents self-contained content.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Semantic', 'Content'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 API is used for offline web applications?',
        problemStatement: 'HTML5 provides APIs for creating offline-capable web applications.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'HTML',
        options: ['Offline API', 'Cache API', 'Service Worker', 'Application Cache'],
        correctAnswer: 'Application Cache',
        explanation: 'Application Cache (AppCache) enables offline web applications.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Offline', 'API'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 element is used for marking up date/time?',
        problemStatement: 'HTML5 provides elements for semantic date and time representation.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'HTML',
        options: ['<date>', '<time>', '<datetime>', '<timestamp>'],
        correctAnswer: '<time>',
        explanation: 'The <time> element is used to represent a specific time or date.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Semantic', 'DateTime'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 attribute specifies the character encoding?',
        problemStatement: 'Character encoding is crucial for proper text display.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'HTML',
        options: ['charset', 'encoding', 'character-set', 'text-encoding'],
        correctAnswer: 'charset',
        explanation: 'The charset attribute specifies the character encoding for the document.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Meta', 'Encoding'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 element is used for sidebar content?',
        problemStatement: 'HTML5 semantic elements define different content sections.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'HTML',
        options: ['<sidebar>', '<aside>', '<side>', '<section>'],
        correctAnswer: '<aside>',
        explanation: 'The <aside> element represents content aside from the main content.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Semantic', 'Layout'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 input type is used for color selection?',
        problemStatement: 'HTML5 provides various input types for different data types.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'HTML',
        options: ['<input type="color">', '<input type="colour">', '<input type="picker">', '<input type="palette">'],
        correctAnswer: '<input type="color">',
        explanation: 'The color input type provides a color picker interface.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Forms', 'Input Types'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 element is used for footer content?',
        problemStatement: 'HTML5 semantic elements define document structure.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'HTML',
        options: ['<footer>', '<bottom>', '<foot>', '<end>'],
        correctAnswer: '<footer>',
        explanation: 'The <footer> element represents the footer of a document or section.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Semantic', 'Layout'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 attribute is used for data storage in elements?',
        problemStatement: 'HTML5 allows custom data attributes in elements.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'HTML',
        options: ['store', 'data', 'storage', 'value'],
        correctAnswer: 'data',
        explanation: 'Data attributes (data-*) are used to store custom data.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Attributes', 'Data'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 element is used for main content?',
        problemStatement: 'HTML5 semantic elements help structure content hierarchy.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'HTML',
        options: ['<main>', '<primary>', '<content>', '<section>'],
        correctAnswer: '<main>',
        explanation: 'The <main> element represents the main content of the document.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Semantic', 'Content'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 input type is used for number input?',
        problemStatement: 'HTML5 provides specialized input types for different data.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'HTML',
        options: ['<input type="numeric">', '<input type="number">', '<input type="integer">', '<input type="digit">'],
        correctAnswer: '<input type="number">',
        explanation: 'The number input type provides a field for numerical input.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Forms', 'Input Types'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 element is used for external content?',
        problemStatement: 'HTML5 provides elements for embedding external content.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'HTML',
        options: ['<external>', '<embed>', '<iframe>', '<object>'],
        correctAnswer: '<iframe>',
        explanation: 'The <iframe> element is used to embed external content.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Embedding', 'External'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 element is used for figure captions?',
        problemStatement: 'HTML5 provides semantic elements for images and captions.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'HTML',
        options: ['<caption>', '<figcaption>', '<figure-caption>', '<img-caption>'],
        correctAnswer: '<figcaption>',
        explanation: 'The <figcaption> element provides a caption for <figure> elements.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Semantic', 'Images'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which HTML5 element is used for grouped content?',
        problemStatement: 'HTML5 semantic elements help organize related content.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'HTML',
        options: ['<group>', '<section>', '<div>', '<container>'],
        correctAnswer: '<section>',
        explanation: 'The <section> element represents a thematic grouping of content.',
        marks: 5,
        timeLimit: 30,
        tags: ['HTML5', 'Semantic', 'Structure'],
        createdBy: adminUser._id
      },

      // CSS Questions (20) - Modern CSS & Frameworks
      {
        questionTitle: 'What does CSS3 stand for?',
        problemStatement: 'CSS3 is the latest version of the CSS standard.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'CSS',
        options: [
          'Cascading Style Sheets 3',
          'Computer Style Sheets 3',
          'Creative Style Sheets 3',
          'Colorful Style Sheets 3'
        ],
        correctAnswer: 'Cascading Style Sheets 3',
        explanation: 'CSS3 stands for Cascading Style Sheets 3.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Styling'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for rounded corners?',
        problemStatement: 'CSS3 introduced properties for enhanced visual effects.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'CSS',
        options: ['corner-radius', 'border-radius', 'round-corners', 'border-round'],
        correctAnswer: 'border-radius',
        explanation: 'The border-radius property creates rounded corners.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Borders', 'Visual'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for box shadows?',
        problemStatement: 'CSS3 provides properties for adding depth to elements.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'CSS',
        options: ['shadow', 'box-shadow', 'drop-shadow', 'element-shadow'],
        correctAnswer: 'box-shadow',
        explanation: 'The box-shadow property adds shadow effects around elements.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Shadows', 'Visual'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for text shadows?',
        problemStatement: 'CSS3 allows text styling with shadow effects.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'CSS',
        options: ['text-shadow', 'font-shadow', 'text-effect', 'shadow-text'],
        correctAnswer: 'text-shadow',
        explanation: 'The text-shadow property adds shadow to text.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Text', 'Shadows'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for gradients?',
        problemStatement: 'CSS3 allows creating gradient backgrounds without images.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'CSS',
        options: ['gradient', 'background-gradient', 'linear-gradient', 'color-gradient'],
        correctAnswer: 'linear-gradient',
        explanation: 'linear-gradient() creates gradient backgrounds.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Gradients', 'Backgrounds'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for transitions?',
        problemStatement: 'CSS3 provides animation capabilities.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'CSS',
        options: ['transition', 'animate', 'transform', 'change'],
        correctAnswer: 'transition',
        explanation: 'The transition property allows smooth CSS property changes.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Transitions', 'Animation'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for 2D transformations?',
        problemStatement: 'CSS3 provides transformation capabilities for elements.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'CSS',
        options: ['transform', 'transform-2d', 'change', 'modify'],
        correctAnswer: 'transform',
        explanation: 'The transform property applies 2D or 3D transformations.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Transforms', 'Animation'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for animations?',
        problemStatement: 'CSS3 provides keyframe animation capabilities.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'CSS',
        options: ['animation', 'animate', 'keyframe', 'motion'],
        correctAnswer: 'animation',
        explanation: 'The animation property applies keyframe animations.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Animation', 'Keyframes'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for flexible box layout?',
        problemStatement: 'CSS3 introduced flexible box layout for better alignment.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'CSS',
        options: ['flex', 'flexbox', 'display-flex', 'box-flex'],
        correctAnswer: 'flex',
        explanation: 'The flex value for display creates a flexible box layout.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Flexbox', 'Layout'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for grid layout?',
        problemStatement: 'CSS3 introduced grid layout for complex layouts.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'CSS',
        options: ['grid', 'grid-layout', 'display-grid', 'layout-grid'],
        correctAnswer: 'grid',
        explanation: 'The grid value for display creates a grid layout.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Grid', 'Layout'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for opacity?',
        problemStatement: 'CSS3 provides transparency control for elements.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'CSS',
        options: ['opacity', 'transparent', 'alpha', 'visibility'],
        correctAnswer: 'opacity',
        explanation: 'The opacity property sets the transparency level.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Opacity', 'Visual'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for multiple backgrounds?',
        problemStatement: 'CSS3 allows multiple background images on elements.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'CSS',
        options: ['backgrounds', 'background-image', 'background', 'multi-background'],
        correctAnswer: 'background',
        explanation: 'The background property accepts multiple image values.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Backgrounds', 'Images'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for column layout?',
        problemStatement: 'CSS3 provides multi-column layout capabilities.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'CSS',
        options: ['columns', 'column-layout', 'multi-column', 'column-count'],
        correctAnswer: 'columns',
        explanation: 'The columns property creates multi-column layouts.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Columns', 'Layout'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for resizing elements?',
        problemStatement: 'CSS3 allows users to resize certain elements.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'CSS',
        options: ['resize', 'resizable', 'user-resize', 'element-resize'],
        correctAnswer: 'resize',
        explanation: 'The resize property controls element resizability.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Resize', 'Interaction'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for word wrapping?',
        problemStatement: 'CSS3 provides text wrapping controls.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'CSS',
        options: ['word-wrap', 'text-wrap', 'wrap', 'overflow-wrap'],
        correctAnswer: 'word-wrap',
        explanation: 'The word-wrap property controls long word wrapping.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Text', 'Wrapping'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for text overflow?',
        problemStatement: 'CSS3 provides text overflow handling.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'CSS',
        options: ['text-overflow', 'overflow-text', 'text-clip', 'text-ellipsis'],
        correctAnswer: 'text-overflow',
        explanation: 'The text-overflow property handles overflowing text.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Text', 'Overflow'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for filter effects?',
        problemStatement: 'CSS3 provides visual filter effects.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'CSS',
        options: ['filter', 'effect', 'visual-filter', 'css-filter'],
        correctAnswer: 'filter',
        explanation: 'The filter property applies visual effects like blur and grayscale.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Filters', 'Visual'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for backdrop filters?',
        problemStatement: 'CSS3 provides backdrop filter effects for modern UI.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'CSS',
        options: ['backdrop-filter', 'filter-backdrop', 'background-filter', 'backdrop-effect'],
        correctAnswer: 'backdrop-filter',
        explanation: 'The backdrop-filter property applies effects to the area behind an element.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Filters', 'Backdrop'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for custom properties?',
        problemStatement: 'CSS3 introduces custom properties (variables).',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'CSS',
        options: ['--variable', 'var', 'custom', 'property'],
        correctAnswer: '--variable',
        explanation: 'Custom properties start with -- (double dash).',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Variables', 'Custom'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which CSS3 property is used for object positioning?',
        problemStatement: 'CSS3 provides object positioning for replaced elements.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'CSS',
        options: ['object-fit', 'object-position', 'fit', 'position-object'],
        correctAnswer: 'object-position',
        explanation: 'The object-position property positions replaced elements.',
        marks: 5,
        timeLimit: 30,
        tags: ['CSS3', 'Objects', 'Positioning'],
        createdBy: adminUser._id
      },

      // JavaScript Questions (20) - Modern ES6+ & Frameworks
      {
        questionTitle: 'What is ES6 in JavaScript?',
        problemStatement: 'ES6 is a major update to JavaScript.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'JavaScript',
        options: [
          'ECMAScript 2015',
          'JavaScript 6',
          'Enhanced Script 6',
          'Enterprise Script 6'
        ],
        correctAnswer: 'ECMAScript 2015',
        explanation: 'ES6 (ECMAScript 2015) is a major JavaScript update.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'JavaScript', 'ECMAScript'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for variable declaration with block scope?',
        problemStatement: 'ES6 introduced new ways to declare variables.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'JavaScript',
        options: ['var', 'let', 'const', 'block'],
        correctAnswer: 'let',
        explanation: 'let declares variables with block scope.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Variables', 'Scope'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for constant variables?',
        problemStatement: 'ES6 provides immutable variable declaration.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'JavaScript',
        options: ['var', 'let', 'const', 'immutable'],
        correctAnswer: 'const',
        explanation: 'const declares variables that cannot be reassigned.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Constants', 'Variables'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for template literals?',
        problemStatement: 'ES6 provides enhanced string literals.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'JavaScript',
        options: ['`', '"', "'", '||'],
        correctAnswer: '`',
        explanation: 'Backticks (`) are used for template literals.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Strings', 'Templates'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for arrow functions?',
        problemStatement: 'ES6 introduced concise function syntax.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'JavaScript',
        options: ['=>', '->', '>>', '&&'],
        correctAnswer: '=>',
        explanation: 'Arrow functions use => syntax.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Functions', 'Arrows'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for destructuring objects?',
        problemStatement: 'ES6 provides destructuring for extracting values.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'JavaScript',
        options: ['{}', '[]', '()', '||'],
        correctAnswer: '{}',
        explanation: 'Object destructuring uses {} syntax.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Destructuring', 'Objects'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for default parameters?',
        problemStatement: 'ES6 allows default parameter values.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'JavaScript',
        options: ['=', 'default', ':', '||'],
        correctAnswer: '=',
        explanation: 'Default parameters use = syntax.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Parameters', 'Functions'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for rest parameters?',
        problemStatement: 'ES6 provides rest parameters for functions.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'JavaScript',
        options: ['...', 'rest', 'args', 'params'],
        correctAnswer: '...',
        explanation: 'Rest parameters use ... syntax.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Parameters', 'Functions'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for spread syntax?',
        problemStatement: 'ES6 provides spread syntax for arrays and objects.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'JavaScript',
        options: ['...', 'spread', 'expand', 'copy'],
        correctAnswer: '...',
        explanation: 'Spread syntax uses ... to expand elements.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Spread', 'Arrays'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for classes?',
        problemStatement: 'ES6 introduced class syntax for OOP.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'JavaScript',
        options: ['class', 'Class', 'object', 'constructor'],
        correctAnswer: 'class',
        explanation: 'The class keyword creates JavaScript classes.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Classes', 'OOP'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for inheritance?',
        problemStatement: 'ES6 classes support inheritance.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'JavaScript',
        options: ['extends', 'inherit', 'super', 'prototype'],
        correctAnswer: 'extends',
        explanation: 'The extends keyword enables class inheritance.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Inheritance', 'Classes'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for modules?',
        problemStatement: 'ES6 introduced module system.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'JavaScript',
        options: ['import', 'require', 'include', 'module'],
        correctAnswer: 'import',
        explanation: 'The import statement imports ES6 modules.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Modules', 'Import'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for promises?',
        problemStatement: 'ES6 introduced promises for async operations.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'JavaScript',
        options: ['Promise', 'promise', 'async', 'future'],
        correctAnswer: 'Promise',
        explanation: 'Promise class handles asynchronous operations.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Promises', 'Async'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for Map objects?',
        problemStatement: 'ES6 introduced new collection types.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'JavaScript',
        options: ['Map', 'map', 'HashMap', 'Dictionary'],
        correctAnswer: 'Map',
        explanation: 'Map is a new collection type in ES6.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Collections', 'Map'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for Set objects?',
        problemStatement: 'ES6 introduced Set for unique values.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'JavaScript',
        options: ['Set', 'set', 'Unique', 'Collection'],
        correctAnswer: 'Set',
        explanation: 'Set stores unique values in ES6.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Collections', 'Set'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for async/await?',
        problemStatement: 'ES2017 introduced async/await for promises.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'JavaScript',
        options: ['async', 'await', 'promise', 'then'],
        correctAnswer: 'async',
        explanation: 'The async keyword enables await usage.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Async', 'Await'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for generators?',
        problemStatement: 'ES6 introduced generator functions.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'JavaScript',
        options: ['function*', 'generator', 'yield', 'async'],
        correctAnswer: 'function*',
        explanation: 'Generator functions use function* syntax.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Generators', 'Functions'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for symbols?',
        problemStatement: 'ES6 introduced symbols as primitive type.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'JavaScript',
        options: ['Symbol', 'symbol', 'sym', 'unique'],
        correctAnswer: 'Symbol',
        explanation: 'Symbol creates unique identifiers in ES6.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Symbols', 'Primitives'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for proxies?',
        problemStatement: 'ES6 introduced proxies for object manipulation.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'JavaScript',
        options: ['Proxy', 'proxy', 'handler', 'trap'],
        correctAnswer: 'Proxy',
        explanation: 'Proxy objects enable custom behavior for operations.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Proxies', 'Meta'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which ES6 feature is used for Reflect API?',
        problemStatement: 'ES6 introduced Reflect for meta-programming.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'JavaScript',
        options: ['Reflect', 'reflect', 'Meta', 'Proxy'],
        correctAnswer: 'Reflect',
        explanation: 'Reflect provides methods for meta-programming.',
        marks: 5,
        timeLimit: 30,
        tags: ['ES6', 'Reflect', 'Meta'],
        createdBy: adminUser._id
      },

      // Python Questions (20) - Modern Python & Data Science
      {
        questionTitle: 'What is Python 3?',
        problemStatement: 'Python 3 is the current major version of Python.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'Python',
        options: [
          'Python version 3.x',
          'Python with 3 features',
          'Enhanced Python',
          'Modern Python'
        ],
        correctAnswer: 'Python version 3.x',
        explanation: 'Python 3 is the current major version series.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Version', 'Basics'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python data type is used for immutable sequences?',
        problemStatement: 'Python provides different sequence types.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'Python',
        options: ['list', 'tuple', 'array', 'sequence'],
        correctAnswer: 'tuple',
        explanation: 'Tuples are immutable sequences in Python.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Data Types', 'Tuple'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python data type is used for key-value pairs?',
        problemStatement: 'Python provides mapping types for data storage.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'Python',
        options: ['dict', 'dictionary', 'map', 'hash'],
        correctAnswer: 'dict',
        explanation: 'dict (dictionary) stores key-value pairs.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Data Types', 'Dictionary'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python data type is used for unique values?',
        problemStatement: 'Python provides sets for unique element storage.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'Python',
        options: ['set', 'unique', 'collection', 'list'],
        correctAnswer: 'set',
        explanation: 'set stores unique values in Python.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Data Types', 'Set'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python feature is used for list comprehensions?',
        problemStatement: 'Python provides concise ways to create lists.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['[]', 'list()', 'comprehension', 'for'],
        correctAnswer: '[]',
        explanation: 'List comprehensions use [] syntax with for loops.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Lists', 'Comprehensions'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python feature is used for lambda functions?',
        problemStatement: 'Python provides anonymous functions.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['lambda', 'def', 'function', 'anonymous'],
        correctAnswer: 'lambda',
        explanation: 'lambda creates anonymous functions in Python.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Functions', 'Lambda'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python module is used for data analysis?',
        problemStatement: 'Python has powerful data analysis libraries.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['pandas', 'numpy', 'matplotlib', 'scipy'],
        correctAnswer: 'pandas',
        explanation: 'pandas is the primary data analysis library in Python.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Data Science', 'Pandas'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python module is used for numerical computing?',
        problemStatement: 'Python provides numerical computing capabilities.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['numpy', 'scipy', 'pandas', 'matplotlib'],
        correctAnswer: 'numpy',
        explanation: 'numpy provides numerical computing in Python.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Numerical', 'NumPy'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python module is used for machine learning?',
        problemStatement: 'Python has extensive machine learning libraries.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['scikit-learn', 'tensorflow', 'pytorch', 'keras'],
        correctAnswer: 'scikit-learn',
        explanation: 'scikit-learn is the primary machine learning library.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Machine Learning', 'Scikit'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python module is used for deep learning?',
        problemStatement: 'Python provides deep learning frameworks.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['tensorflow', 'scikit-learn', 'pandas', 'numpy'],
        correctAnswer: 'tensorflow',
        explanation: 'TensorFlow is a popular deep learning framework.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Deep Learning', 'TensorFlow'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python feature is used for decorators?',
        problemStatement: 'Python provides decorators for function modification.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['@', 'decorator', 'modify', 'enhance'],
        correctAnswer: '@',
        explanation: 'Decorators use @ syntax in Python.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Decorators', 'Functions'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python feature is used for generators?',
        problemStatement: 'Python provides generators for lazy evaluation.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['yield', 'generator', 'return', 'lazy'],
        correctAnswer: 'yield',
        explanation: 'yield creates generator functions in Python.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Generators', 'Yield'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python feature is used for context managers?',
        problemStatement: 'Python provides context managers for resource management.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['with', 'context', 'manage', 'resource'],
        correctAnswer: 'with',
        explanation: 'with statement creates context managers.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Context Managers', 'With'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python module is used for web development?',
        problemStatement: 'Python has popular web frameworks.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['django', 'flask', 'fastapi', 'all of the above'],
        correctAnswer: 'all of the above',
        explanation: 'Python has multiple web frameworks: Django, Flask, FastAPI.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Web Development', 'Frameworks'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python feature is used for type hints?',
        problemStatement: 'Python 3.5+ supports type annotations.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: [':', '->', 'type', 'hint'],
        correctAnswer: ':',
        explanation: 'Type hints use : syntax in Python.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Type Hints', 'Annotations'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python module is used for data visualization?',
        problemStatement: 'Python provides data visualization libraries.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['matplotlib', 'seaborn', 'plotly', 'all of the above'],
        correctAnswer: 'all of the above',
        explanation: 'Python has multiple visualization libraries.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Visualization', 'Plotting'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python feature is used for async programming?',
        problemStatement: 'Python 3.5+ supports async programming.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['async', 'await', 'asyncio', 'all of the above'],
        correctAnswer: 'all of the above',
        explanation: 'Python supports async/await and asyncio.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Async', 'Await'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python module is used for testing?',
        problemStatement: 'Python provides built-in testing frameworks.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'Python',
        options: ['unittest', 'pytest', 'doctest', 'all of the above'],
        correctAnswer: 'all of the above',
        explanation: 'Python has multiple testing frameworks.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'Testing', 'Frameworks'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python feature is used for f-strings?',
        problemStatement: 'Python 3.6+ introduced f-strings.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'Python',
        options: ['f', 'format', 'string', 'interpolate'],
        correctAnswer: 'f',
        explanation: 'f-strings use f prefix for string formatting.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'F-Strings', 'Formatting'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Python module is used for HTTP requests?',
        problemStatement: 'Python provides libraries for HTTP requests.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Python',
        options: ['requests', 'urllib', 'httpx', 'all of the above'],
        correctAnswer: 'all of the above',
        explanation: 'Python has multiple HTTP request libraries.',
        marks: 5,
        timeLimit: 30,
        tags: ['Python3', 'HTTP', 'Requests'],
        createdBy: adminUser._id
      },

      // Java Questions (20) - Modern Java & Enterprise
      {
        questionTitle: 'What is Java 8?',
        problemStatement: 'Java 8 is a major version of Java.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'Java',
        options: [
          'Java version 1.8',
          'Java with 8 features',
          'Enhanced Java',
          'Modern Java'
        ],
        correctAnswer: 'Java version 1.8',
        explanation: 'Java 8 corresponds to version 1.8.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'Version', 'Basics'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 feature is used for lambda expressions?',
        problemStatement: 'Java 8 introduced functional programming.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['->', '=>', 'lambda', 'function'],
        correctAnswer: '->',
        explanation: 'Lambda expressions use -> syntax in Java 8.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'Lambdas', 'Functional'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 feature is used for streams?',
        problemStatement: 'Java 8 introduced stream API.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['Stream', 'stream', 'flow', 'pipeline'],
        correctAnswer: 'Stream',
        explanation: 'Stream API enables functional data processing.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'Streams', 'Functional'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 interface is used for functional interfaces?',
        problemStatement: 'Java 8 introduced functional interfaces.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['Function', 'FunctionalInterface', 'Lambda', 'Stream'],
        correctAnswer: 'FunctionalInterface',
        explanation: '@FunctionalInterface marks functional interfaces.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'Functional', 'Interfaces'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 feature is used for optional values?',
        problemStatement: 'Java 8 introduced Optional to handle null values.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['Optional', 'optional', 'Maybe', 'Nullable'],
        correctAnswer: 'Optional',
        explanation: 'Optional helps avoid NullPointerException.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'Optional', 'Null Safety'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 feature is used for default methods?',
        problemStatement: 'Java 8 allows default methods in interfaces.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['default', 'default method', 'implementation', 'method'],
        correctAnswer: 'default',
        explanation: 'default keyword creates default methods.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'Default Methods', 'Interfaces'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 feature is used for method references?',
        problemStatement: 'Java 8 provides method reference syntax.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['::', '->', '=>', '@'],
        correctAnswer: '::',
        explanation: 'Method references use :: syntax.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'Method References', 'Functional'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 feature is used for repeating annotations?',
        problemStatement: 'Java 8 enhanced annotations support.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'Java',
        options: ['@Repeatable', 'repeatable', 'multiple', 'array'],
        correctAnswer: '@Repeatable',
        explanation: '@Repeatable enables multiple annotations.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'Annotations', 'Repeatable'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 feature is used for type annotations?',
        problemStatement: 'Java 8 introduced type annotations.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'Java',
        options: ['@Target', '@Type', '@Annotation', '@TypeUse'],
        correctAnswer: '@Target',
        explanation: 'Type annotations use @Target annotation.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'Type Annotations', 'Annotations'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 feature is used for Base64 encoding?',
        problemStatement: 'Java 8 added Base64 encoding support.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['Base64', 'base64', 'Encoder', 'Decoder'],
        correctAnswer: 'Base64',
        explanation: 'Base64 class provides encoding/decoding.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'Base64', 'Encoding'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 feature is used for parallel streams?',
        problemStatement: 'Java 8 supports parallel processing.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['parallel()', 'parallelStream()', 'parallelStream', 'parallel'],
        correctAnswer: 'parallelStream()',
        explanation: 'parallelStream() enables parallel processing.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'Parallel', 'Streams'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 feature is used for Nashorn JavaScript engine?',
        problemStatement: 'Java 8 includes a JavaScript engine.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'Java',
        options: ['Nashorn', 'JavaScript', 'Rhino', 'V8'],
        correctAnswer: 'Nashorn',
        explanation: 'Nashorn is the JavaScript engine in Java 8.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'JavaScript', 'Nashorn'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 feature is used for date/time API?',
        problemStatement: 'Java 8 introduced new date/time API.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['java.time', 'datetime', 'date', 'time'],
        correctAnswer: 'java.time',
        explanation: 'java.time package provides new date/time API.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'DateTime', 'API'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java 8 feature is used for CompletableFuture?',
        problemStatement: 'Java 8 enhanced asynchronous programming.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['CompletableFuture', 'Future', 'Async', 'Promise'],
        correctAnswer: 'CompletableFuture',
        explanation: 'CompletableFuture enables async programming.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java8', 'Async', 'Future'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java framework is used for Spring Boot?',
        problemStatement: 'Spring Boot simplifies Java development.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['Spring Boot', 'Spring MVC', 'Spring Data', 'Spring Security'],
        correctAnswer: 'Spring Boot',
        explanation: 'Spring Boot provides rapid application development.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java', 'Spring Boot', 'Framework'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java framework is used for microservices?',
        problemStatement: 'Java has popular microservice frameworks.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['Spring Boot', 'Micronaut', 'Quarkus', 'all of the above'],
        correctAnswer: 'all of the above',
        explanation: 'Java has multiple microservice frameworks.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java', 'Microservices', 'Frameworks'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java build tool is most popular?',
        problemStatement: 'Java uses build tools for project management.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'Java',
        options: ['Maven', 'Gradle', 'Ant', 'all of the above'],
        correctAnswer: 'all of the above',
        explanation: 'Java has multiple build tools available.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java', 'Build Tools', 'Maven'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java testing framework is most popular?',
        problemStatement: 'Java has comprehensive testing frameworks.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'Java',
        options: ['JUnit', 'TestNG', 'Mockito', 'all of the above'],
        correctAnswer: 'all of the above',
        explanation: 'Java has multiple testing frameworks.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java', 'Testing', 'JUnit'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java feature is used for records?',
        problemStatement: 'Java 14+ introduced records for data classes.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'Java',
        options: ['record', 'Record', 'data', 'class'],
        correctAnswer: 'record',
        explanation: 'record creates immutable data classes.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java', 'Records', 'Data Classes'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which Java feature is used for pattern matching?',
        problemStatement: 'Java 14+ introduced pattern matching.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'Java',
        options: ['instanceof', 'pattern', 'match', 'switch'],
        correctAnswer: 'instanceof',
        explanation: 'Pattern matching enhances instanceof operator.',
        marks: 5,
        timeLimit: 30,
        tags: ['Java', 'Pattern Matching', 'Instanceof'],
        createdBy: adminUser._id
      },

      // C++ Questions (20) - Modern C++ & Performance
      {
        questionTitle: 'What is C++11?',
        problemStatement: 'C++11 is a major standard update.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'C++',
        options: [
          'C++ standard 2011',
          'C++ with 11 features',
          'Enhanced C++',
          'Modern C++'
        ],
        correctAnswer: 'C++ standard 2011',
        explanation: 'C++11 was published in 2011.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Standard', 'Basics'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for smart pointers?',
        problemStatement: 'C++11 introduced smart pointers.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['unique_ptr', 'shared_ptr', 'weak_ptr', 'all of the above'],
        correctAnswer: 'all of the above',
        explanation: 'C++11 provides multiple smart pointer types.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Smart Pointers', 'Memory'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for lambda expressions?',
        problemStatement: 'C++11 introduced lambda expressions.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['[]', 'lambda', 'function', '[]()'],
        correctAnswer: '[]',
        explanation: 'Lambda expressions use [] syntax.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Lambdas', 'Functional'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for auto type deduction?',
        problemStatement: 'C++11 introduced automatic type deduction.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'C++',
        options: ['auto', 'automatic', 'deduce', 'infer'],
        correctAnswer: 'auto',
        explanation: 'auto keyword enables type deduction.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Auto', 'Type Deduction'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for range-based for loops?',
        problemStatement: 'C++11 simplified iteration syntax.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'C++',
        options: ['for(:)', 'range for', 'foreach', 'for-each'],
        correctAnswer: 'for(:)',
        explanation: 'Range-based for uses for(:) syntax.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'For Loops', 'Range'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for nullptr?',
        problemStatement: 'C++11 introduced null pointer literal.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'C++',
        options: ['nullptr', 'null', 'NULL', '0'],
        correctAnswer: 'nullptr',
        explanation: 'nullptr is the null pointer literal.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Nullptr', 'Pointers'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for constexpr?',
        problemStatement: 'C++11 introduced compile-time constants.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['constexpr', 'const', 'compile', 'constant'],
        correctAnswer: 'constexpr',
        explanation: 'constexpr enables compile-time evaluation.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Constexpr', 'Compile Time'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for move semantics?',
        problemStatement: 'C++11 introduced move semantics.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['move', 'move()', 'std::move', 'rvalue'],
        correctAnswer: 'std::move',
        explanation: 'std::move enables move semantics.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Move Semantics', 'Performance'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for rvalue references?',
        problemStatement: 'C++11 introduced rvalue references.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['&&', '&', 'rvalue', 'reference'],
        correctAnswer: '&&',
        explanation: '&& denotes rvalue references.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Rvalue', 'References'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for variadic templates?',
        problemStatement: 'C++11 supports variadic templates.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'C++',
        options: ['...', 'variadic', 'template...', 'params'],
        correctAnswer: '...',
        explanation: '... denotes variadic template parameters.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Variadic', 'Templates'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for static_assert?',
        problemStatement: 'C++11 introduced compile-time assertions.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['static_assert', 'assert', 'compile_assert', 'static'],
        correctAnswer: 'static_assert',
        explanation: 'static_assert provides compile-time checks.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Static Assert', 'Compile Time'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for delegating constructors?',
        problemStatement: 'C++11 allows constructor delegation.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['delegating', 'constructor()', 'this()', 'delegate()'],
        correctAnswer: 'this()',
        explanation: 'Constructor delegation uses this() syntax.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Constructors', 'Delegation'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for inherited constructors?',
        problemStatement: 'C++11 allows constructor inheritance.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['using', 'inherit', 'constructor', 'base'],
        correctAnswer: 'using',
        explanation: 'using inherits constructors from base class.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Constructors', 'Inheritance'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for override specifier?',
        problemStatement: 'C++11 provides override specifier.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['override', 'virtual', 'override()', 'specify'],
        correctAnswer: 'override',
        explanation: 'override specifier marks overridden functions.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Override', 'Virtual'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for final specifier?',
        problemStatement: 'C++11 provides final specifier.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['final', 'sealed', 'override', 'virtual'],
        correctAnswer: 'final',
        explanation: 'final specifier prevents further inheritance.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Final', 'Inheritance'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for noexcept?',
        problemStatement: 'C++11 introduced noexcept specifier.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['noexcept', 'throw()', 'noexcept()', 'exception'],
        correctAnswer: 'noexcept',
        explanation: 'noexcept specifies exception guarantees.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Noexcept', 'Exceptions'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for thread library?',
        problemStatement: 'C++11 introduced threading support.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['thread', 'std::thread', 'pthread', 'threading'],
        correctAnswer: 'std::thread',
        explanation: 'std::thread provides threading support.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Threads', 'Concurrency'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for mutex?',
        problemStatement: 'C++11 provides synchronization primitives.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['mutex', 'std::mutex', 'lock', 'synchronize'],
        correctAnswer: 'std::mutex',
        explanation: 'std::mutex provides mutual exclusion.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Mutex', 'Synchronization'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for condition variables?',
        problemStatement: 'C++11 provides condition variables.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'C++',
        options: ['condition_variable', 'condition', 'cv', 'wait'],
        correctAnswer: 'condition_variable',
        explanation: 'condition_variable enables thread synchronization.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Condition Variable', 'Threading'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which C++11 feature is used for atomic operations?',
        problemStatement: 'C++11 provides atomic operations.',
        type: 'MCQ',
        difficulty: 'hard',
        topic: 'C++',
        options: ['atomic', 'std::atomic', 'lockfree', 'atomic<>'],
        correctAnswer: 'std::atomic',
        explanation: 'std::atomic provides lock-free operations.',
        marks: 5,
        timeLimit: 30,
        tags: ['C++11', 'Atomic', 'Lockfree'],
        createdBy: adminUser._id
      },

      // SQL Questions (20) - Modern SQL & Databases
      {
        questionTitle: 'What is SQL?',
        problemStatement: 'SQL is the standard database language.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'SQL',
        options: [
          'Structured Query Language',
          'Simple Query Language',
          'Standard Query Language',
          'System Query Language'
        ],
        correctAnswer: 'Structured Query Language',
        explanation: 'SQL stands for Structured Query Language.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Database', 'Basics'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL clause is used for filtering?',
        problemStatement: 'SQL provides filtering capabilities.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'SQL',
        options: ['WHERE', 'FILTER', 'HAVING', 'GROUP BY'],
        correctAnswer: 'WHERE',
        explanation: 'WHERE clause filters query results.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Clauses', 'Filtering'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL clause is used for sorting?',
        problemStatement: 'SQL provides result sorting.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'SQL',
        options: ['ORDER BY', 'SORT', 'ARRANGE', 'GROUP BY'],
        correctAnswer: 'ORDER BY',
        explanation: 'ORDER BY clause sorts query results.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Clauses', 'Sorting'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL clause is used for grouping?',
        problemStatement: 'SQL provides data grouping.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'SQL',
        options: ['GROUP BY', 'GROUP', 'AGGREGATE', 'SUMMARIZE'],
        correctAnswer: 'GROUP BY',
        explanation: 'GROUP BY clause groups rows with same values.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Clauses', 'Grouping'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL clause is used for joining tables?',
        problemStatement: 'SQL provides table joining.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'SQL',
        options: ['JOIN', 'CONNECT', 'LINK', 'COMBINE'],
        correctAnswer: 'JOIN',
        explanation: 'JOIN clause combines rows from multiple tables.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Joins', 'Tables'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL join type returns all rows from both tables?',
        problemStatement: 'SQL provides different join types.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'SQL',
        options: ['FULL OUTER JOIN', 'INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN'],
        correctAnswer: 'FULL OUTER JOIN',
        explanation: 'FULL OUTER JOIN returns all rows from both tables.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Joins', 'Full Outer'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL join type returns matching rows only?',
        problemStatement: 'SQL provides different join types.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'SQL',
        options: ['INNER JOIN', 'OUTER JOIN', 'LEFT JOIN', 'RIGHT JOIN'],
        correctAnswer: 'INNER JOIN',
        explanation: 'INNER JOIN returns only matching rows.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Joins', 'Inner'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL aggregate function counts rows?',
        problemStatement: 'SQL provides aggregate functions.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'SQL',
        options: ['COUNT()', 'SUM()', 'AVG()', 'MAX()'],
        correctAnswer: 'COUNT()',
        explanation: 'COUNT() function counts number of rows.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Aggregate', 'Count'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL aggregate function calculates average?',
        problemStatement: 'SQL provides aggregate functions.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'SQL',
        options: ['AVG()', 'AVERAGE()', 'MEAN()', 'CALC_AVG()'],
        correctAnswer: 'AVG()',
        explanation: 'AVG() function calculates average values.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Aggregate', 'Average'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL aggregate function finds maximum?',
        problemStatement: 'SQL provides aggregate functions.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'SQL',
        options: ['MAX()', 'MAXIMUM()', 'LARGEST()', 'HIGH()'],
        correctAnswer: 'MAX()',
        explanation: 'MAX() function finds maximum value.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Aggregate', 'Maximum'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL aggregate function finds minimum?',
        problemStatement: 'SQL provides aggregate functions.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'SQL',
        options: ['MIN()', 'MINIMUM()', 'SMALLEST()', 'LOW()'],
        correctAnswer: 'MIN()',
        explanation: 'MIN() function finds minimum value.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Aggregate', 'Minimum'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL aggregate function sums values?',
        problemStatement: 'SQL provides aggregate functions.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'SQL',
        options: ['SUM()', 'TOTAL()', 'ADD()', 'CALC_SUM()'],
        correctAnswer: 'SUM()',
        explanation: 'SUM() function calculates sum of values.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Aggregate', 'Sum'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL constraint ensures unique values?',
        problemStatement: 'SQL provides data integrity constraints.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'SQL',
        options: ['UNIQUE', 'PRIMARY KEY', 'FOREIGN KEY', 'CHECK'],
        correctAnswer: 'UNIQUE',
        explanation: 'UNIQUE constraint ensures all values are unique.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Constraints', 'Unique'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL constraint references another table?',
        problemStatement: 'SQL provides referential integrity.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'SQL',
        options: ['FOREIGN KEY', 'PRIMARY KEY', 'UNIQUE', 'CHECK'],
        correctAnswer: 'FOREIGN KEY',
        explanation: 'FOREIGN KEY references another table.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Constraints', 'Foreign Key'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL constraint checks conditions?',
        problemStatement: 'SQL provides data validation.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'SQL',
        options: ['CHECK', 'VALIDATE', 'CONDITION', 'RULE'],
        correctAnswer: 'CHECK',
        explanation: 'CHECK constraint validates data conditions.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Constraints', 'Check'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL data type stores text?',
        problemStatement: 'SQL provides various data types.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'SQL',
        options: ['VARCHAR', 'TEXT', 'STRING', 'CHAR'],
        correctAnswer: 'VARCHAR',
        explanation: 'VARCHAR stores variable-length text.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Data Types', 'Text'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL data type stores numbers?',
        problemStatement: 'SQL provides numeric data types.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'SQL',
        options: ['INTEGER', 'NUMBER', 'NUMERIC', 'DECIMAL'],
        correctAnswer: 'INTEGER',
        explanation: 'INTEGER stores whole numbers.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Data Types', 'Numbers'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL data type stores dates?',
        problemStatement: 'SQL provides date/time data types.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'SQL',
        options: ['DATE', 'DATETIME', 'TIME', 'TIMESTAMP'],
        correctAnswer: 'DATE',
        explanation: 'DATE stores date values.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'Data Types', 'Date'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL statement creates tables?',
        problemStatement: 'SQL provides DDL statements.',
        type: 'MCQ',
        difficulty: 'easy',
        topic: 'SQL',
        options: ['CREATE TABLE', 'MAKE TABLE', 'NEW TABLE', 'ADD TABLE'],
        correctAnswer: 'CREATE TABLE',
        explanation: 'CREATE TABLE creates new tables.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'DDL', 'Create'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL statement modifies tables?',
        problemStatement: 'SQL provides DDL statements.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'SQL',
        options: ['ALTER TABLE', 'MODIFY TABLE', 'CHANGE TABLE', 'UPDATE TABLE'],
        correctAnswer: 'ALTER TABLE',
        explanation: 'ALTER TABLE modifies existing tables.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'DDL', 'Alter'],
        createdBy: adminUser._id
      },
      {
        questionTitle: 'Which SQL statement removes tables?',
        problemStatement: 'SQL provides DDL statements.',
        type: 'MCQ',
        difficulty: 'medium',
        topic: 'SQL',
        options: ['DROP TABLE', 'DELETE TABLE', 'REMOVE TABLE', 'DESTROY TABLE'],
        correctAnswer: 'DROP TABLE',
        explanation: 'DROP TABLE removes tables completely.',
        marks: 5,
        timeLimit: 30,
        tags: ['SQL', 'DDL', 'Drop'],
        createdBy: adminUser._id
      }
    ];

    const createdQuestions = await Question.insertMany(questions);
    console.log('✅ Created trending questions:', createdQuestions.length);

    // Create comprehensive quizzes with 20 questions each
    const quizzes = [
      {
        title: 'HTML5 Mastery',
        description: 'Comprehensive test of HTML5 and modern web development',
        difficulty: 'medium',
        timeLimit: 40, // 40 minutes for 20 questions
        passingMarks: 70,
        questions: createdQuestions.filter(q => q.topic === 'HTML').map(q => q._id),
        totalMarks: createdQuestions.filter(q => q.topic === 'HTML').reduce((sum, q) => sum + q.marks, 0),
        isRandomized: false,
        isPublished: true,
        createdBy: adminUser._id
      },
      {
        title: 'CSS3 Advanced',
        description: 'Test your CSS3 and modern styling knowledge',
        difficulty: 'medium',
        timeLimit: 40,
        passingMarks: 70,
        questions: createdQuestions.filter(q => q.topic === 'CSS').map(q => q._id),
        totalMarks: createdQuestions.filter(q => q.topic === 'CSS').reduce((sum, q) => sum + q.marks, 0),
        isRandomized: false,
        isPublished: true,
        createdBy: adminUser._id
      },
      {
        title: 'JavaScript ES6+ Expert',
        description: 'Advanced JavaScript with ES6+ and modern features',
        difficulty: 'hard',
        timeLimit: 50,
        passingMarks: 75,
        questions: createdQuestions.filter(q => q.topic === 'JavaScript').map(q => q._id),
        totalMarks: createdQuestions.filter(q => q.topic === 'JavaScript').reduce((sum, q) => sum + q.marks, 0),
        isRandomized: false,
        isPublished: true,
        createdBy: adminUser._id
      },
      {
        title: 'Python Data Science',
        description: 'Python programming with data science and machine learning',
        difficulty: 'hard',
        timeLimit: 50,
        passingMarks: 75,
        questions: createdQuestions.filter(q => q.topic === 'Python').map(q => q._id),
        totalMarks: createdQuestions.filter(q => q.topic === 'Python').reduce((sum, q) => sum + q.marks, 0),
        isRandomized: false,
        isPublished: true,
        createdBy: adminUser._id
      },
      {
        title: 'Java Enterprise',
        description: 'Java programming with enterprise features and frameworks',
        difficulty: 'hard',
        timeLimit: 50,
        passingMarks: 75,
        questions: createdQuestions.filter(q => q.topic === 'Java').map(q => q._id),
        totalMarks: createdQuestions.filter(q => q.topic === 'Java').reduce((sum, q) => sum + q.marks, 0),
        isRandomized: false,
        isPublished: true,
        createdBy: adminUser._id
      },
      {
        title: 'C++ Modern Programming',
        description: 'Modern C++ with C++11+ features and performance optimization',
        difficulty: 'hard',
        timeLimit: 50,
        passingMarks: 75,
        questions: createdQuestions.filter(q => q.topic === 'C++').map(q => q._id),
        totalMarks: createdQuestions.filter(q => q.topic === 'C++').reduce((sum, q) => sum + q.marks, 0),
        isRandomized: false,
        isPublished: true,
        createdBy: adminUser._id
      },
      {
        title: 'SQL Database Expert',
        description: 'Comprehensive SQL and database management',
        difficulty: 'medium',
        timeLimit: 45,
        passingMarks: 70,
        questions: createdQuestions.filter(q => q.topic === 'SQL').map(q => q._id),
        totalMarks: createdQuestions.filter(q => q.topic === 'SQL').reduce((sum, q) => sum + q.marks, 0),
        isRandomized: false,
        isPublished: true,
        createdBy: adminUser._id
      },
      {
        title: 'Full Stack Web Development',
        description: 'Complete web development with HTML5, CSS3, and JavaScript',
        difficulty: 'hard',
        timeLimit: 90,
        passingMarks: 75,
        questions: createdQuestions.filter(q => ['HTML', 'CSS', 'JavaScript'].includes(q.topic)).map(q => q._id),
        totalMarks: createdQuestions.filter(q => ['HTML', 'CSS', 'JavaScript'].includes(q.topic)).reduce((sum, q) => sum + q.marks, 0),
        isRandomized: true,
        isPublished: true,
        createdBy: adminUser._id
      },
      {
        title: 'Programming Languages Mega Challenge',
        description: 'Ultimate test of Python, Java, and C++ programming',
        difficulty: 'hard',
        timeLimit: 120,
        passingMarks: 80,
        questions: createdQuestions.filter(q => ['Python', 'Java', 'C++'].includes(q.topic)).map(q => q._id),
        totalMarks: createdQuestions.filter(q => ['Python', 'Java', 'C++'].includes(q.topic)).reduce((sum, q) => sum + q.marks, 0),
        isRandomized: true,
        isPublished: true,
        createdBy: adminUser._id
      },
      {
        title: 'Complete Software Engineering Challenge',
        description: 'Ultimate test covering all trending software technologies',
        difficulty: 'hard',
        timeLimit: 180,
        passingMarks: 85,
        questions: createdQuestions.map(q => q._id),
        totalMarks: createdQuestions.reduce((sum, q) => sum + q.marks, 0),
        isRandomized: true,
        isPublished: true,
        createdBy: adminUser._id
      }
    ];

    const createdQuizzes = await Quiz.insertMany(quizzes);
    console.log('✅ Created trending quizzes:', createdQuizzes.length);

    console.log('🎉 Trending software courses quiz app seeded successfully!');
    console.log('📚 Available Quizzes:');
    createdQuizzes.forEach((quiz, index) => {
      console.log(`  ${index + 1}. ${quiz.title} (${quiz.questions.length} questions, ${quiz.timeLimit} minutes)`);
    });
    console.log('👤 Admin User: admin@quiz.com / admin@quiz.com');
    console.log('🔢 Total Questions:', createdQuestions.length);
    console.log('🎯 Topics Covered: HTML5 (20), CSS3 (20), JavaScript (20), Python (20), Java (20), C++ (20), SQL (20)');
    console.log('📈 Trending Courses: Web Development, Data Science, Enterprise Java, Modern C++, Database Management');

  } catch (error) {
    console.error('❌ Error seeding trending app:', error);
  } finally {
    await mongoose.disconnect();
  }
}

seedTrendingApp();
